### PR TITLE
plot_var_compare x-axis fixes

### PR DESCRIPTION
**Pull request by lawinslow**
Fixes for Dale.

### CODE REVIEW

**Comment by dzrobert** [comment]
Are we all fixed??

**Comment by lawinslow** [comment]
@dzrobert yup, should be for the x-axis issue you were having. It's not up on GRAN yet though, so unless you want to install it manually, you'll have to wait until our Wednesday update next week. That ok?

**Comment by dzrobert** [comment]
Wednesday is good.   Have you talked to Jordan about generalizing this to all parameters like DO or Total P.

**Comment by lawinslow** [comment]
Failure seems to be a github d/l limit. Merging as it installs clean on my windows machine.

**Pull request merged**
