### PR TITLE
Fixed stage plot function

### PR DESCRIPTION
**Pull request by lawinslow**
It's best when you use functions that already exist...

### CODE REVIEW

**Comment by dzrobert** [comment]
Hey,
 Do I just hit update my packages.  Then it should work??

Thanks
Dale

On Mon, Apr 6, 2015 at 3:17 PM, Luke Winslow <notifications@github.com>
wrote:

> Merged #164 <https://github.com/USGS-R/glmtools/pull/164>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/glmtools/pull/164#event-274504455>.
>



-- 
Dale M. Robertson, PhD
Research Hydrologist                    Telephone # 608-821-3867
U.S. Geological Survey                  Fax #              608-821-3817
Water Science Center                   Email Address: dzrobert@usgs.gov
8505 Research Way                      Office Web Site: wi.water.usgs.gov
Middleton, WI 53562
Personal Web Site: wi.water.usgs.gov/professional-pages/robertson.html

**Comment by dzrobert** [comment]
Hey I am at GLMr 2.0.0.10.0 and glmtools 0.8.1

Should I update both of them??

Dale

On Mon, Apr 6, 2015 at 3:17 PM, Luke Winslow <notifications@github.com>
wrote:

> Merged #164 <https://github.com/USGS-R/glmtools/pull/164>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/glmtools/pull/164#event-274504455>.
>



-- 
Dale M. Robertson, PhD
Research Hydrologist                    Telephone # 608-821-3867
U.S. Geological Survey                  Fax #              608-821-3817
Water Science Center                   Email Address: dzrobert@usgs.gov
8505 Research Way                      Office Web Site: wi.water.usgs.gov
Middleton, WI 53562
Personal Web Site: wi.water.usgs.gov/professional-pages/robertson.html

**Comment by lawinslow** [comment]
We haven't pushed the new glmtools version up to GRAN yet. I'll make a note here when we do. Then you can just hit "update" on your packages and you should get the new version.

**Comment by lawinslow** [comment]
@dzrobert did you get my note that the update is "Now available on GRAN"?

**Pull request merged**
